# Generated by Django 5.2.3 on 2025-06-29 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finditem', '0002_alter_founditem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='founditem',
            name='status',
            field=models.CharField(choices=[('До востребования', 'До востребования'), ('Выдан', 'Выдан'), ('Утилизирован', 'Утилизирован')], default='До востребования', max_length=100, verbose_name='Статус'),
        ),
    ]
